stages:
  train:
    cmd: python src/train.py
    deps:
    - data
    - src
    params:
    - params.yaml:
    outs:
    - models
    metrics:
    - dvclive/metrics.json:
        cache: false
    plots:
    - dvclive/plots:
        cache: false
    - plots:
        cache: false
