name: 🐞 Bug
title: "[Bug]: "
description: Something doesn't behave as it should.
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      placeholder: The car doesnt see a traffic light on Map1.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: The car does see the traffic light on Map1.

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the issue
      placeholder: |
        * Start the simulation with Map1 
        * after 600m the car won't stop at the traffic light.